name: asians-plugin
version: '${project.version}'
main: com.asians.asiansplugin.AsiansPlugin
api-version: 1.21
commands:
  lava:
    description: lava commands
    usage: "Usage: /lava [interval 20] | [start 5] | cancel"
